# Use house data to predict other prices using linear regression in 3D!

## Import libraries and data

In [10]:
import numpy as np
import matplotlib.pyplot as plt

house_data = np.genfromtxt('./Datasets/area_br_price.txt', delimiter=',')
house_data[0]
# Data is grupued by house which is what we want i think, except for the price (Y_0)

array([  2.10400000e+03,   3.00000000e+00,   3.99900000e+05])

## Define features matrix **'X'** and expected values matrix **'Y'**
### We also prepend a 1 to every entry en X as dictated by linear regression heuristics

In [12]:
X = np.delete(house_data, 2, 1)
Y = np.delete(house_data, [0,1], 1)
# this will insert value 1 at positions 0 of X's axis 1
# very nice that np has this feature!
X = np.insert(X, 0, 1, axis=1)
X[0]

array([  1.00000000e+00,   2.10400000e+03,   3.00000000e+00])

## Normalize features matrix

In [6]:
np.shape(X)

(47, 3)

In [93]:
def normalizeFeatures (X):
    for i in range(1, np.shape(X)[1]):
        # isolate one of the features and normalize it
        feature = X.T[i]
        feature -= np.average(feature)
        feature /= (np.amax(feature) - np.amin(feature))
        
normalizeFeatures(X)
X[15]

array([ 1.        ,  0.08254803,  0.20744681])

## We now only need our hypothesis vector
### We will use this vector to get an estimate of the price of the house, we will have to tweak the vectors entries (3 in this case) so that the results match the prices given by house_data ('Y')
> In order to develop intuition about this function, we can think about θ0 as the basic price of a house, θ1 as the price per square meter, θ2 as the price per floor, etc. x1 will be the number of square meters in the house, x2 the number of floors, etc.

In [125]:
# thetaV is a vector with the dimensions of the number of parameters + 1
# X is the features matrix (columns with 1, size, room nb)
# Y is the vector holding the real values (price)
def costFunction (thetaV, X, Y):
    #Yt is the vector with the values that i think are correct
    dataPints = np.shape(Y)[0]
    Yt = np.dot(X, thetaV)
    Yt = Yt.reshape(dataPints, 1) #change shape so it will match Y as a column (T would not work)
    dif = Yt - Y
    sq = np.sqrt(np.square(dif))
    sm = np.sum(sq)
    avg = sm / dataPints
    cost = avg
    return cost # more or less represents how far away we are in avg to the real value

costFunction(np.array([400000,500000,10000]), X, Y)
# $70_000 is not that bad

72969.844870942412

## Try to visualize the cost function as a function of th1, the size of the house